# Build the manuscript-facing supplemental figure set from the source-output
# mapping defined below.
#
# This script does not recalculate the mapped analyses. It copies their current
# outputs, except Figure S10, which is redrawn from the exported physical-driver
# data as absolute values with month-specific climatologies.

suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(patchwork)
  library(ragg)
  library(magick)
})

source("scripts/main_analysis/shared_aesthetics.R")

project_root <- normalizePath(".", winslash = "/")
source_dir <- file.path(project_root, "figures", "supplemental")
final_dir <- Sys.getenv(
  "CALDOR_SUPPLEMENTAL_FINAL_DIR",
  unset = file.path(project_root, "figures", "supplemental_final")
)
processed_dir <- file.path(project_root, "data", "processed")
dir.create(final_dir, recursive = TRUE, showWarnings = FALSE)

# Preserve the previously numbered S6-S9 products before shifting them to
# S7-S10. The archive is intentionally write-once so repeated builds do not
# replace the pre-renumbering set.
renumber_archive <- file.path(final_dir, "archived", "pre_simper_s6_2026-09-16")
dir.create(renumber_archive, recursive = TRUE, showWarnings = FALSE)
prior_numbered_files <- c(
  list.files(final_dir, pattern = "^Figure_S6_page[0-9]+_.*\\.(png|pdf)$", full.names = TRUE),
  file.path(final_dir, c(
    "Figure_S7_schmidt_stability.png", "Figure_S7_schmidt_stability.pdf",
    "Figure_S8_leptolyngbya_2011_2012.png", "Figure_S8_leptolyngbya_2011_2012.pdf",
    "Figure_S9a_values_climatology_2011_2012.png",
    "Figure_S9a_values_climatology_2011_2012.pdf",
    "Figure_S9b_values_climatology_2021_2022.png",
    "Figure_S9b_values_climatology_2021_2022.pdf",
    "Figure_S9_panel_inventory.csv", "supplemental_final_manifest.csv"
  ))
)
prior_numbered_files <- prior_numbered_files[file.exists(prior_numbered_files)]
walk(prior_numbered_files, function(path) {
  destination <- file.path(renumber_archive, basename(path))
  if (!file.exists(destination)) {
    archived <- file.copy(path, destination, copy.date = TRUE)
    if (!archived) stop("Could not archive prior supplemental file: ", path)
  }
})

# Remove only superseded files from earlier assembly conventions so the final
# directory cannot contain conflicting old and new numbering.
stale_final_files <- file.path(final_dir, c(
  "Figure_S6A_radiative_recovery.png",
  "Figure_S6B_nutrient_recovery.png",
  "Figure_S6C_runoff_recovery.png",
  "Figure_S6D_biological_recovery.png",
  "Figure_S6a_radiative_recovery.png",
  "Figure_S6b_nutrient_recovery.png",
  "Figure_S6c_runoff_recovery.png",
  "Figure_S6d_biological_recovery.png",
  "Figure_S9A_values_climatology_2011_2012.png",
  "Figure_S9B_values_climatology_2021_2022.png",
  "Figure_S7_schmidt_stability.png",
  "Figure_S7_schmidt_stability.pdf",
  "Figure_S8_leptolyngbya_2011_2012.png",
  "Figure_S8_leptolyngbya_2011_2012.pdf",
  "Figure_S9a_values_climatology_2011_2012.png",
  "Figure_S9a_values_climatology_2011_2012.pdf",
  "Figure_S9b_values_climatology_2021_2022.png",
  "Figure_S9b_values_climatology_2021_2022.pdf",
  "Figure_S9_panel_inventory.csv",
  "Figure_2020_nutrients_historical_comparison.png",
  "Figure_2020_nutrients_historical_comparison.pdf",
  "Figure_2020_nutrients_historical_comparison_caption.txt",
  "Table_S1_pathway_resistance_recovery.docx",
  "Table_S1_pathway_resistance_recovery.md",
  "Table_S1_pathway_resistance_recovery.tsv"
))
unlink(stale_final_files[file.exists(stale_final_files)])

# The pathway script labels each page independently. Remove prior S6 page
# variants after archiving them, preventing stale labels
# from coexisting with the refreshed page set.
stale_s6_pages <- list.files(
  final_dir,
  pattern = "^Figure_S6_page[0-9]+_.*\\.(png|pdf)$",
  full.names = TRUE
)
unlink(stale_s6_pages)
remaining_stale_s6 <- stale_s6_pages[file.exists(stale_s6_pages)]
if (length(remaining_stale_s6) > 0L) {
  stop(
    "Could not remove archived, superseded S6 page files: ",
    paste(basename(remaining_stale_s6), collapse = ", ")
  )
}

# Render the promoted, two-panel abundance-SIMPER figure from the authoritative
# export generated by the former Figure 5 analysis.
sys.source(
  "scripts/main_analysis/figure_5_simper_supplement.R",
  envir = new.env(parent = globalenv())
)

# Table S1 is a formula-derived mixed-layer rescaling of the supplied ash table.
# A figure-only staging build may skip this unchanged table to avoid rewriting
# its processed-data provenance record.
if (Sys.getenv("CALDOR_SUPPLEMENTAL_SKIP_TABLE_REBUILD", unset = "0") != "1") {
  source("scripts/ash_deposition_mixed_layer_table.R")
}

required_file <- function(path) {
  if (!file.exists(path)) stop("Required source is missing: ", path)
  path
}

copy_output <- function(source, destination) {
  required_file(source)
  if (file.exists(destination) &&
      identical(unname(tools::md5sum(source)), unname(tools::md5sum(destination)))) {
    return(invisible(destination))
  }
  ok <- file.copy(source, destination, overwrite = TRUE, copy.date = TRUE)
  if (!ok) stop("Could not copy ", source, " to ", destination)
  invisible(destination)
}

slugify <- function(x) {
  x %>%
    str_to_lower() %>%
    str_replace_all("[^a-z0-9]+", "_") %>%
    str_replace_all("^_|_$", "")
}

add_outer_label <- function(image, label, label_height = 100, point_size = 54) {
  info <- image_info(image)
  canvas <- image_extent(
    image,
    geometry = sprintf("%dx%d", info$width, info$height + label_height),
    gravity = "south",
    color = "white"
  )
  image_annotate(
    canvas,
    label,
    gravity = "northwest",
    location = "+28+16",
    size = point_size,
    weight = 700,
    color = "black",
    font = "Times New Roman"
  )
}

combine_vertical <- function(sources, labels, destination) {
  if (length(sources) != length(labels)) stop("sources and labels must align")
  images <- map2(sources, labels, function(path, label) {
    add_outer_label(image_read(required_file(path)), label)
  })
  image_write(image_append(image_join(images), stack = TRUE), destination)
  invisible(destination)
}

label_single <- function(source, label, destination) {
  image_write(add_outer_label(image_read(required_file(source)), label), destination)
  invisible(destination)
}

# Figures whose current mapped output is already a single manuscript-facing image.
copy_output(
  file.path(source_dir, "supplemental_smoke_days_hms_pm25_annual.png"),
  file.path(final_dir, "Figure_S1_historical_smoke_days.png")
)
copy_output(
  file.path(source_dir, "supplemental_smoke_days_hms_pm25_annual.pdf"),
  file.path(final_dir, "Figure_S1_historical_smoke_days.pdf")
)
copy_output(
  file.path(source_dir, "supplemental_runoff_discharge_nutrients_2021_2022.png"),
  file.path(final_dir, "Figure_S3_post_fire_runoff.png")
)
copy_output(
  file.path(source_dir, "supplemental_runoff_discharge_nutrients_2021_2022.pdf"),
  file.path(final_dir, "Figure_S3_post_fire_runoff.pdf")
)
copy_output(
  file.path(source_dir, "figure_5", "supplemental_figure_5a_upper_lower_2005_2025.png"),
  file.path(final_dir, "Figure_S5_community_departure_recovery.png")
)
copy_output(
  file.path(source_dir, "figure_5", "supplemental_figure_5a_upper_lower_2005_2025.pdf"),
  file.path(final_dir, "Figure_S5_community_departure_recovery.pdf")
)
copy_output(
  file.path(project_root, "figures", "figure_5_nmds_braycurtis", "archived",
            "revised_analysis", "figure_S6_simper_taxon_contributions.png"),
  file.path(final_dir, "Figure_S6_simper_taxon_contributions.png")
)
copy_output(
  file.path(project_root, "figures", "figure_5_nmds_braycurtis", "archived",
            "revised_analysis", "figure_S6_simper_taxon_contributions.pdf"),
  file.path(final_dir, "Figure_S6_simper_taxon_contributions.pdf")
)
copy_output(
  file.path(project_root, "figures", "figure_5_nmds_braycurtis", "archived",
            "revised_analysis", "figure_S6_simper_taxon_contributions_data.csv"),
  file.path(final_dir, "Figure_S6_simper_taxon_contributions_data.csv")
)
copy_output(
  file.path(project_root, "figures", "figure_5_nmds_braycurtis", "archived",
            "revised_analysis", "figure_S6_simper_taxon_contributions_caption.txt"),
  file.path(final_dir, "Figure_S6_simper_taxon_contributions_caption.txt")
)
copy_output(
  file.path(source_dir, "ctd_profiles_2019_2023", "ctd_schmidt_stability_mltp_2019_2023.png"),
  file.path(final_dir, "Figure_S8_schmidt_stability.png")
)
copy_output(
  file.path(source_dir, "ctd_profiles_2019_2023", "ctd_schmidt_stability_mltp_2019_2023.pdf"),
  file.path(final_dir, "Figure_S8_schmidt_stability.pdf")
)

# The abundance counterpart remains an unnumbered candidate. The 2020 nutrient
# contrast is now S11 because it supports an explicit manuscript claim.
walk2(
  c(
    file.path(project_root, "figures", "figure_4_phytoplankton", "figure_4_abundance_final.png"),
    file.path(project_root, "figures", "figure_4_phytoplankton", "figure_4_abundance_final.pdf"),
    file.path(source_dir, "nutrients_2020_historical", "supplemental_2020_nutrients_historical_comparison.png"),
    file.path(source_dir, "nutrients_2020_historical", "supplemental_2020_nutrients_historical_comparison.pdf"),
    file.path(source_dir, "nutrients_2020_historical", "supplemental_2020_nutrients_caption.txt")
  ),
  c(
    file.path(final_dir, "Figure_phytoplankton_abundance.png"),
    file.path(final_dir, "Figure_phytoplankton_abundance.pdf"),
    file.path(final_dir, "Figure_S11_2020_nutrients_historical_comparison.png"),
    file.path(final_dir, "Figure_S11_2020_nutrients_historical_comparison.pdf"),
    file.path(final_dir, "Figure_S11_2020_nutrients_historical_comparison_caption.txt")
  ),
  copy_output
)

# The GAM-based winter-destabilization synthesis is the selected Figure S12.
walk2(
  c(
    file.path(source_dir, "leptolyngbya_gam_winter_destabilization", "leptolyngbya_gam_winter_destabilization.png"),
    file.path(source_dir, "leptolyngbya_gam_winter_destabilization", "leptolyngbya_gam_winter_destabilization.pdf"),
    file.path(source_dir, "leptolyngbya_gam_winter_destabilization", "leptolyngbya_gam_winter_destabilization_caption.txt")
  ),
  c(
    file.path(final_dir, "Figure_S12_leptolyngbya_gam_winter_destabilization.png"),
    file.path(final_dir, "Figure_S12_leptolyngbya_gam_winter_destabilization.pdf"),
    file.path(final_dir, "Figure_S12_leptolyngbya_gam_winter_destabilization_caption.txt")
  ),
  copy_output
)

# Manuscript-facing composites are generated directly by their source scripts
# at 5 x 6 in or smaller. This avoids raster down-scaling and preserves >8 pt
# text. All component panels are horizontal and use lowercase tags.
walk2(
  c(
    file.path(source_dir, "supplemental_S2_nutrient_timeseries_horizontal.png"),
    file.path(source_dir, "supplemental_S2_nutrient_timeseries_horizontal.pdf"),
    file.path(source_dir, "taxa_profiles", "taxa_profiles_leptolyngbya_2021_2022_abundance_horizontal.png"),
    file.path(source_dir, "taxa_profiles", "taxa_profiles_leptolyngbya_2021_2022_abundance_horizontal.pdf"),
    file.path(source_dir, "taxa_profiles", "taxa_profiles_leptolyngbya_2011_2012_abundance_horizontal.png"),
    file.path(source_dir, "taxa_profiles", "taxa_profiles_leptolyngbya_2011_2012_abundance_horizontal.pdf")
  ),
  c(
    file.path(final_dir, "Figure_S2_nutrient_timeseries.png"),
    file.path(final_dir, "Figure_S2_nutrient_timeseries.pdf"),
    file.path(final_dir, "Figure_S4_leptolyngbya_2021_2022.png"),
    file.path(final_dir, "Figure_S4_leptolyngbya_2021_2022.pdf"),
    file.path(final_dir, "Figure_S9_leptolyngbya_2011_2012.png"),
    file.path(final_dir, "Figure_S9_leptolyngbya_2011_2012.pdf")
  ),
  copy_output
)

# Figure S7 is deliberately split into pages of at most six panels. The source
# script restarts lowercase panel labels on each page and writes both final-size
# PNG and vector PDF files.
pathway_manifest <- read_csv(
  file.path(source_dir, "resistance_and_resilience",
            "resistance_resilience_pathway_plot_manifest.csv"),
  show_col_types = FALSE
)
walk(seq_len(nrow(pathway_manifest)), function(i) {
  row <- pathway_manifest[i, ]
  stem <- sprintf(
    "Figure_S7_page%02d_%s_panels_%s-%s",
    i, slugify(row$Pathway), row$first_panel, row$last_panel
  )
  copy_output(row$plot_file, file.path(final_dir, paste0(stem, ".png")))
  copy_output(row$pdf_file, file.path(final_dir, paste0(stem, ".pdf")))
})

# Table S2 accompanies Figure S7 and is copied in editable and paste-ready forms.
table_dir <- file.path(source_dir, "resistance_and_resilience")
walk(c(
  "pathway_resistance_resilience_word_table.docx",
  "pathway_resistance_resilience_word_table.md",
  "pathway_resistance_resilience_word_paste.tsv"
), function(name) {
  extension <- tools::file_ext(name)
  copy_output(
    file.path(table_dir, name),
    file.path(final_dir, paste0("Table_S2_pathway_resistance_recovery.", extension))
  )
})

# ---- Figure S10: absolute values with focal-year-excluded climatologies -----

BASE_FAMILY <- "Times New Roman"
CALDOR_START <- as.Date("2021-08-14")
CALDOR_END <- as.Date("2021-10-21")
LEPTO_2011_START <- as.Date("2011-04-16")
LEPTO_2011_END <- as.Date("2012-03-21")
LEPTO_2021_END <- as.Date("2022-07-31")
LEPTO_DEPTH_COLS <- c("0-40 m" = "#1B9E77", "60-105 m" = "#0072B2")

drivers_native <- read_csv(
  required_file(file.path(processed_dir, "physical_drivers_compiled.csv")),
  show_col_types = FALSE
) %>%
  mutate(date = as.Date(date))

mixed_layer_depth_native <- read_csv(
  required_file(file.path(processed_dir, "mltp_mixed_layer_depth_density_2005_2025.csv")),
  show_col_types = FALSE
) %>%
  transmute(date = as.Date(date), variable = "mixed_layer_depth_m", value = as.numeric(mld_m)) %>%
  filter(is.finite(value))

# LTP Secchi depth is used because the other optical and biological series on
# this figure are LTP measurements. Retain individual observations so the
# observed line and the month-specific historical reference use the same data.
secchi_native <- read_csv(
  required_file(file.path(
    project_root, "data", "lake_environmental_data", "secchi", "Secchi_LTP.csv"
  )),
  show_col_types = FALSE
) %>%
  transmute(
    date = as.Date(substr(Date_Time_Local, 1, 10)),
    variable = "secchi_depth_m",
    value = suppressWarnings(as.numeric(Secchi))
  ) %>%
  filter(!is.na(date), is.finite(value), value > 0)

# Use the same historical/recent LTP merge used by the Figure 4 workflow, but
# summarize concentration within the established biological depth zones. The
# result is a mean concentration in ug/L, not a depth-integrated areal value.
chl_ltp_recent <- read_csv(
  required_file(file.path(
    project_root, "data", "lake_environmental_data", "chla", "Tahoe_LTP_Chl.csv"
  )),
  show_col_types = FALSE
) %>%
  transmute(
    station = "LTP", date = as.Date(Date), depth = as.numeric(Depth),
    chla_ugl = as.numeric(Chla)
  ) %>%
  filter(!is.na(date), is.finite(depth), is.finite(chla_ugl))

chl_all_raw <- tryCatch(
  read.csv(
    required_file(file.path(
      project_root, "data", "lake_environmental_data", "chla", "terc_chla_all.csv"
    )),
    quote = "", stringsAsFactors = FALSE
  ),
  error = function(e) read.csv(
    required_file(file.path(
      project_root, "data", "lake_environmental_data", "chla", "terc_chla_all.csv"
    )),
    quote = "", stringsAsFactors = FALSE, fill = TRUE, comment.char = ""
  )
)

chl_hist_ltp <- chl_all_raw %>%
  as_tibble() %>%
  filter(Sample_Type %in% c("FIELD", "FLDDUP"), Station_ID == "Index") %>%
  transmute(
    station = "LTP", date = as.Date(Date),
    depth = suppressWarnings(as.numeric(Depth)),
    chla_ugl = suppressWarnings(as.numeric(Chla))
  ) %>%
  filter(!is.na(date), is.finite(depth), is.finite(chla_ugl), chla_ugl > 0)

chla_zone_native <- bind_rows(
  anti_join(chl_hist_ltp, chl_ltp_recent, by = c("station", "date", "depth")),
  chl_ltp_recent
) %>%
  filter(depth >= 0, depth <= 105, chla_ugl >= 0, chla_ugl < 50) %>%
  group_by(date, depth) %>%
  summarise(chla_ugl = mean(chla_ugl, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    depth_zone = case_when(
      depth <= 40 ~ "0-40 m",
      depth >= 60 & depth <= 105 ~ "60-105 m",
      TRUE ~ NA_character_
    ),
    variable = recode(
      depth_zone,
      "0-40 m" = "chla_0_40_ugl",
      "60-105 m" = "chla_60_105_ugl"
    )
  ) %>%
  filter(!is.na(depth_zone)) %>%
  group_by(date, variable, depth_zone) %>%
  summarise(value = mean(chla_ugl, na.rm = TRUE), .groups = "drop")

supplemental_depth_native <- bind_rows(
  mixed_layer_depth_native %>% mutate(depth_zone = NA_character_),
  secchi_native %>% mutate(depth_zone = NA_character_),
  chla_zone_native
)

drivers_native <- bind_rows(
  drivers_native,
  supplemental_depth_native %>% select(date, variable, value)
)

drivers_monthly <- read_csv(
  required_file(file.path(processed_dir, "physical_drivers_monthly.csv")),
  show_col_types = FALSE
) %>%
  mutate(month_date = as.Date(month_date))

supplemental_depth_monthly <- supplemental_depth_native %>%
  mutate(year = year(date), month = month(date)) %>%
  group_by(variable, year, month) %>%
  summarise(value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  mutate(month_date = as.Date(sprintf("%04d-%02d-15", year, month)))

drivers_monthly <- bind_rows(
  drivers_monthly %>%
    filter(!variable %in% unique(supplemental_depth_monthly$variable)),
  supplemental_depth_monthly
)

lepto_monthly <- read_csv(
  required_file(file.path(
    project_root, "data", "lake_environmental_data", "phytoplankton",
    "caldor_fire_phytoplankton_LTP_2005_2025_selected_depths.csv"
  )),
  show_col_types = FALSE
) %>%
  transmute(
    date = floor_date(as.Date(date), "month") + days(14),
    depth_zone = depth_bin,
    taxon,
    value = suppressWarnings(as.numeric(abundance))
  ) %>%
  filter(
    taxon == "Leptolyngbya spp.",
    depth_zone %in% names(LEPTO_DEPTH_COLS),
    !is.na(value)
  ) %>%
  group_by(date, depth_zone) %>%
  summarise(value = mean(value, na.rm = TRUE), .groups = "drop")

DEP_UNIT <- "mg m⁻² d⁻¹"
LAKE_UNIT <- "µg L⁻¹"
variable_spec <- tribble(
  ~variable,                     ~title,                               ~ylab,                                  ~color,
  "surface_temp_c",              "Surface temperature (0-10 m)",       "Temperature\n(°C)",                      "#DE4E6A",
  "pm25_ugm3",                   "PM2.5",                              "PM2.5\n(µg m⁻³)",                        "#5831B8",
  "upper_truckee_discharge_cms", "Upper Truckee River discharge",      "Discharge\n(m³ s⁻¹)",                    "#BC5090",
  "din_srp_deposition_molar",    "Deposition DIN:SRP (molar)",         "DIN:SRP\n(molar)",                       "#E65100",
  "din_srp_inlake_molar",        "In-lake DIN:TRP (molar, 0-10 m)",    "DIN:TRP\n(molar)",                       "#1565C0",
  "par_1pct_depth_m",            "1% PAR depth",                       "1% PAR depth\n(m)",                      "#2E7D32",
  "secchi_depth_m",              "Secchi depth",                       "Depth (m)",                              "#00838F",
  "schmidt_stability_j_m2",      "Stratification (Schmidt stability)", "Stability\n(J m⁻²)",                    "#5E35B1",
  "mixed_layer_depth_m",         "Mixed-layer depth",                  "Depth (m)",                              "#8C510A",
  "no3_deposition_mgm2d",        "Deposition NO3",                     paste0("NO3 (", DEP_UNIT, ")"),             "#E65100",
  "no3_inlake_ugl",              "In-lake NO3 (0-10 m)",               paste0("NO3 (", LAKE_UNIT, ")"),            "#1565C0",
  "nh4_deposition_mgm2d",        "Deposition NH4",                     paste0("NH4 (", DEP_UNIT, ")"),             "#BF360C",
  "nh4_inlake_ugl",              "In-lake NH4 (0-10 m)",               paste0("NH4 (", LAKE_UNIT, ")"),            "#0D47A1",
  "tkn_deposition_mgm2d",        "Deposition TKN",                     paste0("TKN (", DEP_UNIT, ")"),             "#F57F17",
  "tkn_inlake_ugl",              "In-lake TKN (0-10 m)",               paste0("TKN (", LAKE_UNIT, ")"),            "#01579B",
  "srp_deposition_mgm2d",        "Deposition SRP",                     paste0("SRP (", DEP_UNIT, ")"),             "#AD1457",
  "srp_inlake_ugl",              "In-lake TRP (0-10 m)",               paste0("TRP (", LAKE_UNIT, ")"),            "#4527A0"
)

# S10 is contextual rather than a duplicate of the complete nutrient figure.
# Retaining one stoichiometric indicator per source keeps the figure readable
# at final journal size; individual nutrient species remain in Figure S2.
s10_core_variables <- c(
  "surface_temp_c", "pm25_ugm3", "upper_truckee_discharge_cms",
  "din_srp_deposition_molar", "din_srp_inlake_molar", "par_1pct_depth_m",
  "secchi_depth_m", "schmidt_stability_j_m2", "mixed_layer_depth_m"
)

panel_theme <- function(show_x) {
  result <- theme_bw(base_size = LO_FONT_MIN_PT, base_family = BASE_FAMILY) +
    theme(
      panel.grid.minor = element_blank(),
      axis.title.y = element_text(size = LO_FONT_MIN_PT,
                                  lineheight = 0.9,
                                  margin = margin(r = 1, unit = "pt")),
      axis.text = element_text(size = LO_FONT_MIN_PT),
      axis.text.y = element_text(margin = margin(r = 1, unit = "pt")),
      plot.title = element_text(
        size = LO_FONT_MIN_PT, face = "plain", hjust = 0,
        margin = margin(b = 0.5, unit = "mm")
      ),
      plot.margin = margin(0.5, 0.8, 0.5, 0.8, "mm")
    )
  if (!show_x) {
    result <- result + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
  }
  result
}

add_window_markers <- function(plot, window_kind) {
  if (window_kind == "2011") {
    plot
  } else {
    plot +
      annotate(
        "rect", xmin = CALDOR_START, xmax = CALDOR_END,
        ymin = -Inf, ymax = Inf, fill = "firebrick", alpha = 0.07
      )
  }
}

s10_date_labels <- function(x, window_kind) {
  labels <- format(x, "%b")
  if (window_kind != "2011" && length(x) > 0L) {
    first_year_tick <- !duplicated(year(x))
    labels[first_year_tick] <- paste0(
      labels[first_year_tick], "\n", year(x[first_year_tick])
    )
  }
  labels
}

climatology_for_window <- function(variable_id, window_start, window_end, exclude_years) {
  monthly_reference <- drivers_monthly %>%
    filter(variable == variable_id, !year %in% exclude_years) %>%
    group_by(month) %>%
    summarise(
      mean = mean(value, na.rm = TRUE),
      sd = sd(value, na.rm = TRUE),
      n = sum(is.finite(value)),
      .groups = "drop"
    ) %>%
    mutate(
      se = sd / sqrt(n),
      critical_t = if_else(n >= 2, qt(0.975, n - 1), NA_real_),
      lower = mean - critical_t * se,
      upper = mean + critical_t * se
    )

  tibble(date = seq(floor_date(window_start, "month"), floor_date(window_end, "month"), by = "month")) %>%
    mutate(month = month(date)) %>%
    left_join(monthly_reference, by = "month")
}

make_driver_panel <- function(variable_id, title, ylab, color, window_start,
                              window_end, exclude_years, window_kind, show_x) {
  observed <- drivers_native %>%
    filter(variable == variable_id, date >= window_start, date <= window_end, is.finite(value))
  if (nrow(observed) == 0) return(NULL)

  climatology <- climatology_for_window(variable_id, window_start, window_end, exclude_years)
  plot <- ggplot() %>% add_window_markers(window_kind)
  plot <- plot +
    geom_ribbon(
      data = climatology,
      aes(date, ymin = lower, ymax = upper),
      fill = "grey75", alpha = 0.45, na.rm = TRUE
    ) +
    geom_line(
      data = climatology,
      aes(date, mean),
      color = "grey35", linetype = "dashed", linewidth = LO_LW_THIN,
      na.rm = TRUE
    ) +
    geom_line(
      data = observed,
      aes(date, value),
      color = color, linewidth = LO_LW_MID, alpha = 0.9, na.rm = TRUE
    )
  if (variable_id %in% c("din_srp_deposition_molar", "din_srp_inlake_molar")) {
    plot <- plot + geom_hline(yintercept = 16, linetype = "dotted", color = "black")
  }
  if (variable_id %in% c(
    "par_1pct_depth_m", "mixed_layer_depth_m", "secchi_depth_m"
  )) {
    plot <- plot + scale_y_reverse()
  }
  plot +
    scale_x_date(
      limits = c(window_start, window_end),
      date_breaks = "2 months",
      labels = function(x) s10_date_labels(x, window_kind),
      expand = expansion(mult = 0.01)
    ) +
    labs(
      x = NULL, y = ylab,
      title = if (variable_id %in% c("mixed_layer_depth_m", "secchi_depth_m")) {
        title
      } else {
        NULL
      }
    ) +
    panel_theme(show_x)
}

make_chla_panel <- function(window_start, window_end, exclude_years,
                            window_kind, show_x) {
  observed <- chla_zone_native %>%
    filter(
      date >= floor_date(window_start, "month"),
      date <= floor_date(window_end, "month")
    )

  variable_depth_map <- c(
    "chla_0_40_ugl" = "0-40 m",
    "chla_60_105_ugl" = "60-105 m"
  )
  climatology <- imap_dfr(variable_depth_map, function(depth_zone, variable_id) {
    climatology_for_window(
      variable_id, window_start, window_end, exclude_years
    ) %>%
      mutate(depth_zone = depth_zone)
  })

  plot <- ggplot() %>% add_window_markers(window_kind)
  plot +
    geom_ribbon(
      data = climatology,
      aes(date, ymin = lower, ymax = upper, fill = depth_zone),
      alpha = 0.12, colour = NA, na.rm = TRUE
    ) +
    geom_line(
      data = climatology,
      aes(date, mean, colour = depth_zone, group = depth_zone),
      linetype = "dashed", linewidth = LO_LW_THIN, alpha = 0.75,
      na.rm = TRUE
    ) +
    geom_line(
      data = observed,
      aes(date, value, colour = depth_zone, group = depth_zone),
      linewidth = LO_LW_MID, alpha = 0.95, na.rm = TRUE
    ) +
    scale_colour_manual(values = LEPTO_DEPTH_COLS, guide = "none") +
    scale_fill_manual(values = LEPTO_DEPTH_COLS, guide = "none") +
    scale_x_date(
      limits = c(window_start, window_end),
      date_breaks = "2 months",
      labels = function(x) s10_date_labels(x, window_kind),
      expand = expansion(mult = 0.01)
    ) +
    labs(
      x = NULL,
      y = expression(mu * "g L"^-1),
      title = "Chlorophyll a"
    ) +
    panel_theme(show_x) +
    theme(legend.position = "none")
}

make_lepto_panel <- function(window_start, window_end, window_kind, show_x) {
  observed <- lepto_monthly %>%
    filter(date >= floor_date(window_start, "month"), date <= floor_date(window_end, "month"))
  plot <- ggplot(observed, aes(date, value, color = depth_zone, group = depth_zone)) %>%
    add_window_markers(window_kind)
  p <- plot +
    geom_line(linewidth = LO_LW_MID, na.rm = TRUE) +
    scale_x_date(
      limits = c(window_start, window_end),
      date_breaks = "2 months",
      labels = function(x) s10_date_labels(x, window_kind),
      expand = expansion(mult = 0.01)
    ) +
    labs(
      x = NULL,
      y = expression("Cells L"^-1),
      title = expression(italic("Leptolyngbya")~"abundance")
    ) +
    panel_theme(show_x) +
    scale_color_manual(
      values = LEPTO_DEPTH_COLS,
      labels = c("0-40 m", "60-105 m"),
      name = "Depth zone"
    ) +
    theme(legend.position = "bottom", legend.title = element_blank())
}

build_s10_page <- function(window_start, window_end, exclude_years, window_kind,
                          destination, page_label, tag_start) {
  available_spec <- variable_spec %>%
    filter(variable %in% s10_core_variables) %>%
    rowwise() %>%
    mutate(
      n_window = sum(
        drivers_native$variable == variable &
          drivers_native$date >= window_start &
          drivers_native$date <= window_end &
          is.finite(drivers_native$value)
      )
    ) %>%
    ungroup() %>%
    filter(n_window > 0)

  panels <- pmap(
    available_spec,
    function(variable, title, ylab, color, n_window) {
      make_driver_panel(
        variable, title, ylab, color,
        window_start, window_end, exclude_years, window_kind,
        show_x = FALSE
      )
    }
  )
  panels <- append(panels, list(
    make_chla_panel(
      window_start, window_end, exclude_years, window_kind,
      show_x = window_kind == "2011"
    ),
    make_lepto_panel(window_start, window_end, window_kind, TRUE)
  ))

  tag_theme <- theme(
    plot.tag = element_text(
      size = LO_FS_TAG, face = "bold", family = BASE_FAMILY,
      hjust = 1, vjust = 1
    ),
    plot.tag.position = c(.98, .98)
  )
  if (window_kind == "2011") {
    tag_theme <- tag_theme + theme(
      plot.caption = element_text(size = 8.5, family = BASE_FAMILY, hjust = 0.5,
                                  margin = margin(t = 1.5, unit = "mm"))
    )
  }

  figure <- wrap_plots(panels, ncol = 2, byrow = TRUE, guides = "collect") +
    plot_annotation(
      tag_levels = list(letters[tag_start + seq_along(panels) - 1L]),
      caption = if (window_kind == "2011") "2011-2012" else NULL
    )
  figure <- figure & tag_theme & theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.justification = "center",
    legend.title = element_blank(),
    legend.text = element_text(size = LO_FONT_MIN_PT, family = BASE_FAMILY),
    legend.key.height = unit(1.8, "mm"),
    legend.key.width = unit(3, "mm"),
    legend.spacing.x = unit(1, "mm"),
    legend.margin = margin(0.5, 0.5, 0.5, 0.5, "mm")
  )

  ragg::agg_png(
    destination,
    width = LO_WIDTH_MAX,
    height = LO_HEIGHT_MAX,
    units = "cm",
    res = LO_DPI_LINE
  )
  print(figure)
  invisible(dev.off())
  ggsave(
    paste0(tools::file_path_sans_ext(destination), ".pdf"), figure,
    width = LO_WIDTH_MAX, height = LO_HEIGHT_MAX, units = "cm", device = cairo_pdf
  )

  inventory_variables <- c(
    available_spec$variable,
    "chlorophyll_a_by_depth",
    "leptolyngbya_abundance"
  )
  inventory_titles <- c(
    available_spec$title,
    "Chlorophyll a (0-40 m and 60-105 m)",
    "Leptolyngbya abundance (0-40 m and 60-105 m)"
  )
  tibble(
    page = page_label,
    variable = inventory_variables,
    title = inventory_titles,
    focal_years_excluded_from_climatology = paste(exclude_years, collapse = ";"),
    window_start = as.character(window_start),
    window_end = as.character(window_end)
  )
}

s10_inventory <- bind_rows(
  build_s10_page(
    as.Date("2011-01-01"), as.Date("2012-04-30"), c(2011, 2012), "2011",
    file.path(final_dir, "Figure_S10a_values_climatology_2011_2012.png"), "a", 1L
  ),
  build_s10_page(
    as.Date("2021-04-01"), as.Date("2022-07-31"), c(2021, 2022), "2021",
    file.path(final_dir, "Figure_S10b_values_climatology_2021_2022.png"), "b", 1L
  )
)
write_csv(s10_inventory, file.path(final_dir, "Figure_S10_panel_inventory.csv"))

manifest <- tribble(
  ~figure, ~file, ~construction,
  "S1", "Figure_S1_historical_smoke_days.png", "Copied mapped output at 3.0 x 2.48 in",
  "S2", "Figure_S2_nutrient_timeseries.png", "Deposition and in-lake subplots paired horizontally; upper-right lowercase tags; L&O 5 x 6 in",
  "S3", "Figure_S3_post_fire_runoff.png", "Copied mapped output; year printed only on the first displayed date tick; nutrient concentrations shown in ug/L; only tributary site is retained in the legend",
  "S4", "Figure_S4_leptolyngbya_2021_2022.png", "Monthly abundance depth profiles; abundance on x and reversed depth on y; connected points; biovolume omitted",
  "S5", "Figure_S5_community_departure_recovery.png", "Upper and lower panels stacked in two rows as a-b; fixed pre-fire reference bounds; Bray-Curtis lower limit zero; natural-log Leptolyngbya abundance; line-only",
  "S6", "Figure_S6_simper_taxon_contributions.png", "Former Figure 5 abundance-SIMPER result; upper 0-40 m and lower 60-105 m shown as panels a-b with a common signed contribution scale",
  "S8", "Figure_S8_schmidt_stability.png", "Copied preferred Schmidt-only 2019-2023 output; Caldor label retained; subtitle removed",
  "S9", "Figure_S9_leptolyngbya_2011_2012.png", "Monthly abundance depth profiles; abundance on x and reversed depth on y; connected points; biovolume omitted",
  "S10", "Figure_S10a_values_climatology_2011_2012.png", "Absolute values with focal-year-excluded climatologies; reversed 1% PAR, mixed-layer, and Secchi depth axes; chlorophyll a and Leptolyngbya abundance shown for 0-40 m in green and 60-105 m in blue; two-month ticks labeled only on the bottom row",
  "S10", "Figure_S10b_values_climatology_2021_2022.png", "Absolute values with focal-year-excluded climatologies; reversed 1% PAR, mixed-layer, and Secchi depth axes; chlorophyll a and Leptolyngbya abundance shown for 0-40 m in green and 60-105 m in blue; two-month ticks labeled only on the bottom row; Caldor window shaded",
  "Unnumbered", "Figure_phytoplankton_abundance.png", "Abundance counterpart to main phytoplankton figure; chlorophyll profiles grouped as panel a and depth-zone abundance panels labeled b-c",
  "S11", "Figure_S11_2020_nutrients_historical_comparison.png", "August-October 2020 deposition and 0-10 m nutrients compared with same-month non-2020 observations; point and historical-interval line proportions match Figure 3a; paired PNG/PDF exported at 3.0 in width with retained aspect ratio",
  "S12", "Figure_S12_leptolyngbya_gam_winter_destabilization.png", "Aligned Schmidt stability and density-threshold mixed-layer depth with GAM-fitted 5-90 m Leptolyngbya abundance; mixed-layer depth increases downward on the right axis; Caldor and inflection-date intervals are shown by shading without an inflection text annotation; upper-right internal panel tags; paired 1200-dpi PNG and vector PDF",
  "Table S1", "Table_S1_ash_deposition_mixed_layer.docx", "13-m September 2021 mixed-layer concentration equivalent",
  "Table S2", "Table_S2_pathway_resistance_recovery.docx", "Copied editable recovery table"
)
manifest <- bind_rows(
  manifest %>% filter(figure != "S8"),
  pathway_manifest %>%
    mutate(
      figure = "S7",
      file = sprintf(
        "Figure_S7_page%02d_%s_panels_%s-%s.png",
        row_number(), slugify(Pathway), first_panel, last_panel
      ),
      construction = paste0(
        Pathway, " page ", page, "; page-local panels ",
        first_panel, "-", last_panel, "; at most six panels"
      )
    ) %>%
    select(figure, file, construction),
  manifest %>% filter(figure == "S8")
) %>%
  mutate(
    sort_key = match(figure, c(paste0("S", 1:12), "Table S1", "Table S2"))
  ) %>%
  arrange(sort_key) %>%
  select(-sort_key)
write_csv(manifest, file.path(final_dir, "supplemental_final_manifest.csv"))

message("Final supplemental set saved to: ", final_dir)
